databases:
  - name: monster-db
    databaseName: monster_feed
    user: monster_user

services:
  - type: web
    name: monster-feed-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monster-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
