databases:
  - name: monster-db
    databaseName: monster_feed
    user: monster_user

services:
  - type: web
    name: monster-feed-backend
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt" # Keep the build.sh command
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monster-db
          property: connectionString
      - key: PYTHON_VERSION
        # UPDATED LINE: Use a more general version string
        value: 3.11 
      - key: FLASK_ENV
        value: production
      # Add your Cloudinary credentials in Render dashboard:
      # CLOUDINARY_CLOUD_NAME
      # CLOUDINARY_API_KEY  
      # CLOUDINARY_API_SECRET
