databases:
  - name: monster-db
    databaseName: monster_feed
    user: monster_user

services:
  - type: web
    name: monster-feed-backend
    env: python
    # UPDATED LINE: Run the build script before installing Python packages
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monster-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      # Add your Cloudinary credentials in Render dashboard:
      # CLOUDINARY_CLOUD_NAME
      # CLOUDINARY_API_KEY  
      # CLOUDINARY_API_SECRET
