databases:
  - name: monster-db
    databaseName: monster_feed
    user: monster_user

services:
  - type: web
    name: monster-feed-backend
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    # UPDATED LINE: Use the more robust Gunicorn command from your Procfile
    startCommand: "gunicorn app:app --workers 2 --timeout 120 --keep-alive 5 --max-requests 1000 --preload"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monster-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11 
      - key: FLASK_ENV
        value: production
      # Add your Cloudinary credentials in Render dashboard:
      # CLOUDINARY_CLOUD_NAME
      # CLOUDINARY_API_KEY  
      # CLOUDINARY_API_SECRET
